# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Potess
email: jppotess@gmail.com
description:
  John Potess is an audio engineer turned web developer with an entrepreneur spirit
  and a taste for craft brews and fine dining. Expect the unexpected and prepare 
  yourself for a magical adventure of wonder and amazement.
url: "http://johnpotess.com" # the base hostname & protocol for your site
twitter_username: johnpotess
github_username:  jppotess
paginate: 3
gems: [jekyll-paginate]
paginate_path: "page:num"

# Build settings
markdown: kramdown
permalinks: /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      type: "post"
      author: John Potess
      layout: "post"

    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
      type: "pages"
      author: John Potess





